spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource-h2:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  datasource-mysql:
    url: jdbc:mysql://54.180.133.228:3306/test
    username: admin
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
    open-in-view: false
  data:
    mongodb:
      host: 54.180.133.228
      port: 27017
      authentication-database: admin
      database: admin
      username: admin
      password: 1234
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: alpha
server:
  port: 8081
---