spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
    open-in-view: false
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: alpha
server:
  port: 8081
---