spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:h2:tcp://localhost/~/test   # 로컬 테스트용 H2 DB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create
    open-in-view: false
  servlet:
    ## Multipart properties
    # Enable multipart uploads
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

## 프로젝트내의 폴더에 업로드 파일을 설정하고 싶으면 16번째 줄처럼
## 본인 PC의 특정 dir에 업로드 하고 싶으면 17번쨰 줄처럼 설정한다.
file:
#  upload-dir: ./uploads
    upload-dir: C:\local_work\EricAuction_UploadFiles
server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: alpha
server:
  port: 8081
---